### PR TITLE
Consolidate Auth and Validation in SSE Request Handler

### PR DESCRIPTION
**Pull request by vrajat**
In BaseSingleStageBrokerRequestHandler, authorization steps were in two different places. The 2nd check was added in #14953. Now the checks are consolidated in a single call. One caveat is that for schema related compilation errors, the user should have read permissions else schema info is leaked. This is the same behaviour as introduced in #14953 

QPS validation checks have also been moved up as soon as table name is available.

Functions for MSE have been reused as they are reusable and also with an eye on #10712. In #10712, SSE also has to support multiple physical tables.

### CODE REVIEW

File: pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java [hunk 1]
```diff
@@ -317,4 +323,66 @@ protected void onQueryFinish(long requestId) {
...
+
+    if (!failedTables.isEmpty()) {
+      tableAuthorizationResult = new TableAuthorizationResult(failedTables);
+    } else {
+      tableAuthorizationResult = TableAuthorizationResult.success();
+    }
+
+    if (!tableAuthorizationResult.hasAccess()) {
+      _brokerMetrics.addMeteredGlobalValue(BrokerMeter.REQUEST_DROPPED_DUE_TO_ACCESS_ERROR, 1);
+      LOGGER.warn("Access denied for requestId {}", requestContext.getRequestId());
```
Comment (gortiz) [inline pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java:358]: Are we sure we want to log this as a warning? It could be problematic, especially when it is more needed (e.g., when receiving an attack). The metric should be good enough. BTW, we could also make that metric table based instead of global for more information.

File: pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java [hunk 2]
```diff
@@ -317,4 +323,66 @@ protected void onQueryFinish(long requestId) {
...
+      LOGGER.warn("Request {}: query exceeds quota for database: {}", requestContext.getRequestId(), database);
+      requestContext.setErrorCode(QueryErrorCode.TOO_MANY_REQUESTS);
+      return true;
+    }
+    for (String tableName : tableNames) {
+      if (!_queryQuotaManager.acquire(tableName)) {
+        LOGGER.warn("Request {}: query exceeds quota for table: {}", requestContext.getRequestId(), tableName);
+        requestContext.setErrorCode(QueryErrorCode.TOO_MANY_REQUESTS);
+        String rawTableName = TableNameBuilder.extractRawTableName(tableName);
+        _brokerMetrics.addMeteredTableValue(rawTableName, BrokerMeter.QUERY_QUOTA_EXCEEDED, 1);
```
Comment (gortiz) [inline pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java:382]: Same here. Logging as WARN seems to be overkill. We have the metric for that.

**Comment by gortiz** [comment]
> One caveat is that for schema related compilation errors, the user should have read permissions else schema info is leaked.

Can you give some examples of the old/new behavior when users have/don't have permissions and the query is compatible/incompatible with the schema?

File: pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java (hunk 1 above)
Comment (vrajat) [reply pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java:358]: This code is copied as is from `MultiStageBrokerRequestHandler`. I can remove it if required.

File: pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java (hunk 2 above)
Comment (vrajat) [reply pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java:382]: This code is copied as is from `MultiStageBrokerRequestHandler`. I can remove it if required.

**Comment by vrajat** [comment]
> > One caveat is that for schema related compilation errors, the user should have read permissions else schema info is leaked.
> 
> Can you provide some examples of the old/new behavior when users have/don't have permissions and the query is compatible/incompatible with the schema?

This PR moves the auth check added in #14953 into an if condition. I did this based on an offline conversation where we discussed that this extra check is messing up the compilation and auth time reported in metrics. At least in the successful path, the reported execution time is correct.

The original PR also doesnt have a test. @bziobrowski Is there a test already for this condition or did you test it manually ?

**Comment by gortiz** [comment]
My main concern is actually the not-so-happy path: What happens when a user without permissions tries to do stuff? We should not fail by saying "table X doesn't exist" if the user cannot read that table. TBH I don't know what do we return right now in cases like this, but given you explicitly mentioned a change in the error if the user doesn't have permissions, I wanted to ask.

**Comment by vrajat** [comment]
> My main concern is actually the not-so-happy path: What happens when a user without permissions tries to do stuff? We should not fail by saying "table X doesn't exist" if the user cannot read that table. TBH I don't know what do we return right now in cases like this, but given you explicitly mentioned a change in the error if the user doesn't have permissions, I wanted to ask.

Oh no - no change in the error message. IIUC correctly,
* Before #14953 a UNKNOWN_COLUMN error was thrown even if the user had no access to the table.
* #14953 added an auth check in mainline before checking for UNKNOWN_COLUMN path. 
* This PR adds this check only if UNKNOWN_COLUMN error happened. 

The check is now executed in `hasTableAccess` in the auth phase if there are no other errors.

So it was #14953 that changed the error. This PR keeps the same behaviour as #14953

**Review by gortiz — APPROVED** [review]
